//
// Created by Kelo Deng on 2020/10/22.
//

#ifndef MULTI_LINUX_DATA_TRANSMISSION_SYSTEM_GLOBAL_H
#define MULTI_LINUX_DATA_TRANSMISSION_SYSTEM_GLOBAL_H

# define BIT_SIZE 256

#endif //MULTI_LINUX_DATA_TRANSMISSION_SYSTEM_GLOBAL_H
